// Facts about the project the app shows. Dates and rubric text come from PROJECT_PLAN.md
// and the assignment ("SWE 380/CSC 580 Group Project", V2026.09.10), quoted where marked.
// Each deliverable names the GitHub issue that carries it, so its status is live.

export const TEAM = [
  { login: "jeraddunne", name: "Jerad Dunne", role: "Product Owner", rater: "jd", profile: "docs/team/jerad-dunne.md", onboarding: null },
  { login: "angel06la", name: "Leticia Aderhold", role: "Scrum Master", rater: "la", profile: "docs/team/leticia-aderhold.md", onboarding: 50 },
  { login: "AllieHgs", name: "Allie Hodges", role: "Developer / Researcher", rater: "ah", profile: "docs/team/allie-hodges.md", onboarding: 51 },
  { login: "hinak786", name: "Hina Kramer", role: "Developer / Researcher", rater: "hk", profile: "docs/team/hina-kramer.md", onboarding: 52 },
];

export const memberByLogin = (login) =>
  TEAM.find((m) => m.login.toLowerCase() === String(login || "").toLowerCase()) || null;

export const LINKS = {
  repo: "https://github.com/jeraddunne/csc580-group9-msr2027",
  board: "https://github.com/users/jeraddunne/projects/1",
  site: "https://jeraddunne.github.io/csc580-group9-msr2027/",
  invitation: "https://github.com/jeraddunne/csc580-group9-msr2027/invitations",
  newKey:
    "https://github.com/settings/tokens/new?scopes=public_repo,project&description=Group%209%20Project%20Guide",
  keys: "https://github.com/settings/tokens",
  file: (path) => `https://github.com/jeraddunne/csc580-group9-msr2027/blob/main/${path}`,
  issue: (n) => `https://github.com/jeraddunne/csc580-group9-msr2027/issues/${n}`,
  pull: (n) => `https://github.com/jeraddunne/csc580-group9-msr2027/pull/${n}`,
  raw: (path) => `https://raw.githubusercontent.com/jeraddunne/csc580-group9-msr2027/main/${path}`,
};

export const QUESTION =
  "In the GitSkills July 2026 sample, how prevalent are skill instructions and bundled scripts that enable risk-relevant capabilities, do skills carrying them reach more repositories through verbatim copying, and do modified variants of the same skill add or remove those capabilities?";

// Phases in order. `milestone` is the GitHub milestone title.
export const PHASES = [
  {
    id: "formation",
    name: "Formation",
    milestone: "Formation",
    dmaic: "Define",
    start: "2026-09-10",
    end: "2026-09-16",
    weight: 10,
    purpose: "Form groups, inspect datasets, identify feasible topics, create repositories, and draft candidate questions.",
    deliverable: "Topic brief and initial backlog",
    review: "docs/sprints/00-formation/review.md",
    rubric: [
      { text: "Topic selection, research question, and initial backlog", issues: [5, 41] },
      { text: "Team working agreement signed by all four members", issues: [1] },
    ],
    youCan: [
      "Sign the team charter (Documents)",
      "Fill in your profile (Documents)",
    ],
  },
  {
    id: "s1",
    name: "Sprint 1",
    milestone: "Sprint 1",
    dmaic: "Measure",
    start: "2026-09-17",
    end: "2026-10-07",
    weight: 20,
    purpose: "Finalize the research question, define variables, acquire or sample data, build the first pipeline, and establish reproducibility.",
    deliverable: "Sprint 1 research-and-data package",
    review: "docs/sprints/sprint-1/review.md",
    rubric: [
      { text: "A selected MSR-inspired topic and a precise research question.", issues: [12] },
      { text: "Motivation, expected contribution, and at least one competing or simpler explanation.", issues: [12] },
      { text: "A defined unit of analysis, population, sample, variables, and outcome measures.", issues: [13] },
      { text: "Dataset acquisition or sampling instructions and a data dictionary.", issues: [14] },
      { text: "A first working data-loading and extraction pipeline.", issues: [15] },
      { text: "At least one exploratory table or visualization generated by code.", issues: [16] },
      { text: "A repository with issues, milestones, branch protection or equivalent review practice, and a first pull request.", issues: [17] },
      { text: "A retrospective explaining what the group learned and what changed in the backlog.", issues: [20] },
    ],
    acceptance:
      "The question is answerable with the selected data; the data path is documented; the pipeline runs on an approved sample; at least one result is generated; and the group has identified the primary risks and threats to validity.",
    youCan: [
      "Sign the charter and open your first pull request (Documents)",
      "Run the fresh-run check on your own computer and record it (Learn: test environments, then Documents)",
      "Review a pull request and say what you checked (Reviews)",
      "Present one step of the Oct 7 demo",
    ],
  },
  {
    id: "s2",
    name: "Sprint 2",
    milestone: "Sprint 2",
    dmaic: "Analyze",
    start: "2026-10-08",
    end: "2026-10-28",
    weight: 20,
    purpose: "Implement the core mining or analysis method, add tests and validation, and produce preliminary results.",
    deliverable: "Sprint 2 implementation-and-evidence package",
    review: "docs/sprints/sprint-2/review.md",
    rubric: [
      { text: "A working implementation of the core mining, extraction, similarity, classification, traceability, or visualization method.", issues: [21] },
      { text: "Automated tests for important parsing, transformation, matching, or metric functions.", issues: [22] },
      { text: "A validation sample, manual annotation protocol, or other evaluation design.", issues: [23] },
      { text: "Preliminary results with reproducible figures or tables.", issues: [24] },
      { text: "At least one pull request reviewed by a different team member than the author.", issues: [] },
      { text: "An updated research report containing the background, method, implementation, and preliminary results.", issues: [25] },
      { text: "A retrospective that records changes to the research question, method, scope, or interpretation.", issues: [26] },
    ],
    acceptance:
      "The core implementation runs end to end on the approved sample; the method is tested; the group can explain why the result should be trusted or where it may fail; and the preliminary analysis is supported by generated evidence rather than screenshots alone.",
    youCan: [
      "Label your validation items, if you are a rater (Learn: checking the checker)",
      "Review pull requests (Reviews)",
      "Write or check a report section",
    ],
  },
  {
    id: "s3",
    name: "Sprint 3",
    milestone: "Sprint 3",
    dmaic: "Improve",
    start: "2026-10-29",
    end: "2026-11-18",
    weight: 25,
    purpose: "Complete the analysis, conduct robustness checks, improve figures, draft the report, and prepare the demonstration.",
    deliverable: "Sprint 3 complete draft and demonstration",
    review: "docs/sprints/sprint-3/review.md",
    rubric: [
      { text: "Final or near-final results addressing the research question.", issues: [27] },
      { text: "Robustness checks, sensitivity analysis, or comparison across meaningful subgroups.", issues: [28] },
      { text: "Error analysis and manually inspected examples.", issues: [29] },
      { text: "Final figures and tables generated from the repository pipeline.", issues: [30] },
      { text: "A complete draft report with citations and a clear separation between findings and interpretation.", issues: [31] },
      { text: "A threat-to-validity section addressing dataset bias, measurement error, confounding, missing data, reproducibility, and generalizability.", issues: [32] },
      { text: "A documented release or tagged version of the repository.", issues: [33] },
      { text: "A final demonstration plan and presentation materials.", issues: [34] },
      { text: "A retrospective identifying the group's most important process improvement.", issues: [35] },
    ],
    acceptance:
      "A new user can follow the README to reproduce the primary results; the report answers the question with evidence; limitations are explicit; and all major artifacts are traceable to issues, commits, pull requests, or decisions.",
    youCan: ["Inspect examples for the error analysis", "Prepare your part of the presentation", "Reproduce the results from the README"],
  },
  {
    id: "break",
    name: "Break",
    milestone: null,
    dmaic: "",
    start: "2026-11-19",
    end: "2026-11-29",
    weight: 0,
    purpose: "Thanksgiving break (Nov 26).",
    rubric: [],
    youCan: [],
  },
  {
    id: "final",
    name: "Finalization",
    short: "Final",
    milestone: "Finalization",
    dmaic: "Control",
    start: "2026-11-30",
    end: "2026-12-04",
    weight: 20,
    purpose: "Respond to feedback, finalize the repository and report, present results, and submit individual reflections.",
    deliverable: "Final report, repository release, and presentation",
    review: "docs/sprints/finalization/checklist.md",
    rubric: [
      { text: "Respond to feedback and finalize the report.", issues: [36] },
      { text: "Repository release v1.0.0 and a fresh-machine reproduction by a non-author.", issues: [37] },
      { text: "Final presentation and live demonstration.", issues: [38] },
      { text: "Every member has documented an individual contribution and reflection (5%).", issues: [39] },
      { text: "The AI-use log (and disclosure) is complete.", issues: [40] },
    ],
    acceptance: "Final submission checklist in the assignment: approved question and dataset, accessible repository, README reproduction, clean-environment run, complete history, regenerable tables and figures, results separate from interpretation, threats and limitations, AI-use log, and every member's reflection.",
    youCan: ["Write your individual reflection", "Rehearse the presentation"],
  },
];

export const START = "2026-09-10";
export const END = "2026-12-04";

export function currentPhase(today) {
  return PHASES.find((p) => today >= p.start && today <= p.end) || (today < START ? PHASES[0] : PHASES[PHASES.length - 1]);
}

// Key dates that are not phase boundaries.
export const KEY_DATES = [
  { date: "2026-10-01", text: "Check-in 2; ADR-0007 decided" },
  { date: "2026-10-07", text: "Sprint 1 review and retrospective" },
  { date: "2026-10-13", text: "Round 1 labels: signals and lineage (Jerad)" },
  { date: "2026-10-16", text: "Round 1 labels: drift (Leticia and Jerad)" },
  { date: "2026-10-27", text: "Validation scored: precision and agreement" },
  { date: "2026-10-28", text: "Sprint 2 review" },
  { date: "2026-11-18", text: "Sprint 3 review: draft, release, demo plan" },
  { date: "2026-12-04", text: "Final presentation, report, reflections" },
];
